### ISSUE TITLE
How can we collect Txs up to some amount?

### ISSUE THREAD

**Issue by giuscri** [NAGTeam/btclient#6]
How can we collect Txs up to some amount querying the blockchain "by hand"?

**Comment by giuscri** [comment]
Maybe we can find this article useful, but it's probably **true**-**pro**-hackish. I think I'll give me a try, otherwise the entire project has serious chances to stuck at the point we're now if I don't understand better the protocol.

[Using the raw Bitcoin protocol](http://www.righto.com/2014/02/bitcoins-hard-way-using-raw-bitcoin.html)

**Comment by aronnebrivio** [comment]
http://bitcoin.stackexchange.com/questions/4301/what-is-an-unspent-output

**Comment by giuscri** [comment]
There are **NO** bitcoins _unspent_. There are unspent **outputs**, instead!!

See the link above.

We need to traverse over the txs array until we've stored enough coins. For each transaction, push into `txs` an object like

```
{ txhash: ..., outputindex: ..., value: ...}
```

whenever the output address is the same as `fromaddress` and the output is not spent yet.

**Comment by giuscri** [comment]
once we have that array of txs,  we're finally ready to use Bitcoinjs, building the transaction.

**Comment by giuscri** [comment]
Done.
